services:
  - docker

git:
  lfs_skip_smudge: true

language: python

branches:
  only:
    - master

before_install:
  - docker pull veros/ubuntu:16.04

install:
  - docker build -t veros -f testing.dockerfile .

env:
  global:
    - PYOM_DIR=/usr/local/lib
  matrix:
    - VEROS_BACKEND=numpy PYTHON_EXEC=python2 PYOM2_LIB=$PYOM_DIR/pyOM_code_py2.so
    - VEROS_BACKEND=bohrium BH_STACK=openmp PYTHON_EXEC=python2 PYOM2_LIB=$PYOM_DIR/pyOM_code_py2.so
    - VEROS_BACKEND=bohrium BH_STACK=opencl PYTHON_EXEC=python2 PYOM2_LIB=$PYOM_DIR/pyOM_code_py2.so
    - VEROS_BACKEND=numpy PYTHON_EXEC=python3 PYOM2_LIB=$PYOM_DIR/pyOM_code_py3.so
    - VEROS_BACKEND=bohrium BH_STACK=openmp PYTHON_EXEC=python3 PYOM2_LIB=$PYOM_DIR/pyOM_code_py3.so
    - VEROS_BACKEND=bohrium BH_STACK=opencl PYTHON_EXEC=python3 PYOM2_LIB=$PYOM_DIR/pyOM_code_py3.so

script:
  - "docker run -e BH_STACK -t veros $PYTHON_EXEC -c \"\
      import bohrium; \
      print(bohrium.bh_info.info()) \
      \"\
    "
  - "docker run \
      `bash <(curl -s https://codecov.io/env)` \
      -e BH_STACK -e VEROS_BACKEND -t veros \
      /bin/bash -c \"\
          $PYTHON_EXEC -m pytest -v --cov=veros --pyom2-lib $PYOM2_LIB test && codecov \
      \"\
    "

notifications:
  email: false
