services:
  - docker

git:
  lfs_skip_smudge: true

language: python

branches:
  only:
    - master

before_install:
  - docker pull veros/ubuntu:17.10

install:
  - docker build -t veros -f testing.dockerfile .

env:
  global:
    - PYOM_DIR=/usr/local/lib
    - OMP_NUM_THREADS=1
  matrix:
    - VEROS_BACKEND=numpy PYTHON_EXEC=python2 PYOM2_LIB=$PYOM_DIR/pyOM_code_py2.so
    - VEROS_BACKEND=bohrium BH_STACK=openmp PYTHON_EXEC=python2 PYOM2_LIB=$PYOM_DIR/pyOM_code_py2.so
    - VEROS_BACKEND=bohrium BH_STACK=opencl PYTHON_EXEC=python2 PYOM2_LIB=$PYOM_DIR/pyOM_code_py2.so
    - VEROS_BACKEND=numpy PYTHON_EXEC=python3 PYOM2_LIB=$PYOM_DIR/pyOM_code_py3.so
    - VEROS_BACKEND=bohrium BH_STACK=openmp PYTHON_EXEC=python3 PYOM2_LIB=$PYOM_DIR/pyOM_code_py3.so
    - VEROS_BACKEND=bohrium BH_STACK=opencl PYTHON_EXEC=python3 PYOM2_LIB=$PYOM_DIR/pyOM_code_py3.so

script:
  - "docker run -e BH_STACK -t veros $PYTHON_EXEC -c \"\
      import bohrium; \
      print(bohrium.bh_info.info()) \
      \"\
    "
  - "docker run \
      -e CODECOV_TOKEN -e VEROS_BACKEND -e BH_STACK -e OMP_NUM_THREADS -t veros \
      /bin/bash -c \"\
          $PYTHON_EXEC -m pytest -v --cov --pyom2-lib $PYOM2_LIB --backend $VEROS_BACKEND . && codecov \
      \"\
    "

notifications:
  email: false
