name: veros

channels:
    - conda-forge

dependencies:
    - python=3.8
    - pip
    - click
    - entrypoints
    - requests
    - numpy
    - scipy
    - h5netcdf
    - h5py
    - pillow
    - loguru
    - tqdm
    - cython
    - pip:
        - -e .
