name: veros
channels:
    - conda-forge
dependencies:
    - python=3.7
    - numpy
    - click
    - requests>=2.18
    - numpy>=1.13
    - scipy
    - h5netcdf
    - h5py
    - pillow
    - ruamel.yaml
    - future
    - pyamg
    - gcc
    - loguru
    - tqdm
    - pip:
        - bohrium
        - -e .
