name: veros
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - numpy
    - click
    - requests>=2.18
    - numpy>=1.13
    - scipy
    - h5netcdf
    - h5py
    - pillow
    - ruamel.yaml
    - libgcc
    - loguru
    - tqdm
    - pip:
        - -e .
